### ISSUE TITLE
.snapshots included in new snapshots

### ISSUE THREAD

**Issue by Jip-Hop** [nachoparker/btrfs-snp#1]
I've scheduled btrfs-snp as per your example:

```
# cat > /etc/cron.hourly/btrfs-snp <<EOF
#!/bin/bash
/usr/local/sbin/$BIN /home hourly  24 3600
/usr/local/sbin/$BIN /home daily    7 86400
/usr/local/sbin/$BIN /home weekly   4 604800
/usr/local/sbin/$BIN /     weekly   4 604800
/usr/local/sbin/$BIN /home monthly 12 2592000
EOF
chmod +x /etc/cron.hourly/btrfs-snp
```

But instead I take snapshots of a data disk at `/mnt/data`.
I noticed that the `.snapshots` folder is included in each snapshot.
Because of this, inside a snapshot at `/mnt/data/.snapshots/timestamp`, there's another `.snapshot` folder.

Is this normal, or did I set it up wrong?

With only a couple of snapshots this already got quite confusing but I also worry that this will quickly fill up the drive. When an old snapshot is deleted from the 'main' snapshot folder at `/mnt/data/.snapshots/`, will that snapshot (and corresponding data) also be removed from the newer snapshots that include the old snapshot in their .snapshot folder?

**Comment by nachoparker** [comment]
Hi,

> Because of this, inside a snapshot at /mnt/data/.snapshots/timestamp, there's another .snapshot folder.

That is normal. The `/mnt/data/.snapshots/<xx>/.snapshots` should be empty. You can store your snapshots in a different place if you want, adding another parameter at the end.

```
# btrfs-snp
Usage: btrfs-snp <dir> (<tag>) (<limit>) (<seconds>) (<destdir>)
```

> I also worry that this will quickly fill up the drive.

Snapshots don't take additional space, because this is a COW filesystem. The only thing is that in order to free space for a file you have to delete the real file and all snapshots containing it.

**Comment by Jip-Hop** [comment]
You're right! The `/mnt/data/.snapshots/<xx>/.snapshots/<xx>` folders are empty. I didn't expect those folders to be there at all. I was so surprised that I forgot to check if the actual snapshot data was inside them. Sorry, no cause for alarm. Case closed.
