### ISSUE TITLE
crontab sending noisy emails

### ISSUE THREAD

**Issue by j4jes** [nachoparker/btrfs-snp#3]
Just thought I'd mention everything is working fine for me on a centos6 machine accept the hourly cron is sending me this:

`/etc/cron.hourly/snap-cfd-home:`

`/usr/local/sbin/btrfs-snp: line 69: SNAPS: bad array subscript`
`Create a readonly snapshot of '/home/data/cfd' in '/home/data/cfd/.snapshots`
`/hourly_2018-12-05_140101`
`snapshot hourly_2018-12-05_140101 generated`
`/usr/local/sbin/btrfs-snp: line 69: SNAPS: bad array subscript`
`No new snapshot needed for daily`
`/usr/local/sbin/btrfs-snp: line 69: SNAPS: bad array subscript`
`No new snapshot needed for weekly`
`/usr/local/sbin/btrfs-snp: line 69: SNAPS: bad array subscript`
`No new snapshot needed for monthly`

So do I just put >/dev/null 2>&1  on the end of each line ?

**Comment by j4jes** [comment]
So I had a closer look at this, and for some reason only my hourly snapshots are working, because the script encounters an error on line66 when it tries to determine the age of previous snapshots with that tag.

[root@cayenne cron.daily]# /usr/local/sbin/btrfs-snp /home/data/cfd hourly  24 3600
/usr/local/sbin/btrfs-snp: line 66: SNAPS: bad array subscript
Create a readonly snapshot of '/home/data/cfd' in '/home/data/cfd/.snapshots/hourly_2019-01-08_111847'
snapshot hourly_2019-01-08_111847 generated
[root@cayenne cron.daily]# /usr/local/sbin/btrfs-snp /home/data/cfd daily   30 86400
/usr/local/sbin/btrfs-snp: line 66: SNAPS: bad array subscript
No new snapshot needed for daily
[root@cayenne cron.daily]# /usr/local/sbin/btrfs-snp /home/data/cfd daily   30 8640
/usr/local/sbin/btrfs-snp: line 66: SNAPS: bad array subscript
Create a readonly snapshot of '/home/data/cfd' in '/home/data/cfd/.snapshots/daily_2019-01-08_112051'
snapshot daily_2019-01-08_112051 generated
[root@cayenne cron.daily]# 

For now I'm just going to set the seconds to 0, and make separate entries in cron.daily, cron.weekly, etc. I should still impose a a limit as to how many snapshots it keeps.

**Comment by nachoparker** [comment]
Hello,

That is quite curious, because there is a check for the size of `SNAPS`, like this `[[ "${#SNAPS[@]}" != 0 ]] && ...`

Could you add the line `set -x` at the beginning of the function and try again, then paste your output here so we can see what's going on?

Thanks for reporting
