### ISSUE TITLE
2 daily use inconviencies ;)

### ISSUE THREAD

**Issue by DrStoop** [nachoparker/btrfs-snp#4]
Hi nachoparker,
thanks a lot for the scripts! I just based my new backup system on it for `/` aka `@` and /home aka ` @home. Everything works very smooth. I  just want to point out two daily cases which caused some confusion:
- default setting of `.snapshots` within the snapshotted subvolume: I restore e.g. my root bakup by:
```sh
$ sudo mv @ @_old
$ sudo mv @_backup @
$ sudo btrfs subvolume delete @_old
```
The last command fails because the snapshots/subvolumes are stored within the to-be-delete-subvolume. I bypassed this by creating a new subvolume for all my backups and store them there. I may be more useful to set the default snapshots-folder next to the subvolume instead of inside the subvolume  ...just thinking:)
- `btrfs-sync` identifies user-defined local paths with '@'-characters in a folder name as server address: I name subvolumes with '@'-prefix to distinguish them from regular folder when mounted. `btrfs-sync` thinks paths with '@' are remote servers and tries to ssh -connect. I just made a `btrfs-local-sync` and hacked out the server address detection. 

Unforunately I'm a really bad basher otherwise I would have committed some viable suggestions :(

Thanks & Greets!

**Comment by phillcoxon** [comment]
+1 the issue of trying to restore a snapshot when the snapshots are stored in the same subvolume :D 
I think having a separate subvolume for snapshots is a great idea and it would be worth mentioning this on the wiki.

**Comment by nachoparker** [comment]
I see. If you prefer to have the snapshots folder outside you can still do it by passing your desired destination as the fifth parameter, right?

For instance

```
sudo btrfs-snp /home snapshot 0 0 /home-snapshots
```

(it would store it in `/home-snapshots` instead)

Thanks for reporting

edit: I'll close but we can keep talking.
