### ISSUE TITLE
subvolume detection

### ISSUE THREAD

**Issue by mrhotio** [nachoparker/btrfs-snp#5]
OS: Ubuntu 18.04.2
Btrfs pool: /pool
Subvolume: /pool/subvolume

The following piece of code:
```
btrfs subvolume show "$DIR" | grep -q "${DIR}$" ||
```
failed for me when snapshotting a valid subvolume.

Changing it to:
```
btrfs subvolume show "$DIR" | grep -q "$(basename "${DIR}$")" ||
```
fixed the issue for me.

**Comment by mrhotio** [comment]
I think a more elegant way could be this:
```
  [[ $(stat --format=%i "${DIR}") -eq 256 ]] || {
    echo "$DIR is not a BTRFS subvolume"
    return 1
  }
```
imo

**Comment by nachoparker** [comment]
Hi,

What was the content of `$DIR` that made it fail? `btrfs subvolume show` should always work on a valid subvolume path

Thanks for reporting

**Comment by nachoparker** [comment]
I ran into this when I switched to Buster. Fixed
